version: "2"

services:

  eureka:
    image: eureka
    container_name: eureka-server1
    ports:
      - "8761:8761"

  config:
    image: config
    container_name: config-server1
    ports:
      - "8888:8888"

  mysql:
    image: mysql
    container_name: mysql1
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1A60mhJs
    ports:
      - "3307:3306"
    volumes:
      - C:\data-mysql:/var/lib/mysql

  db:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - C:\data-mongo:/data/db


  gateway:
    image: gateway
    container_name: gateway-server1
    ports:
      - "9090"

  admin:
    image: admin
    container_name: admin-server1
    ports:
      - "9091"

  hystrix:
    image: hystrix
    container_name: hystrix-server1
    ports:
      - "9092"

  config:
    image: config
    container_name: config-server1
    ports:
      - "9093"

  turbine:
    image: turbine
    container_name: turbine-server1
    ports:
      - "9094"

  cliente:
    image: cliente
    container_name: cliente-service1
    ports:
      - "8080"

  visita:
    image: visita
    container_name: visita-service1
    ports:
      - "8081"

  factura:
    image: factura
    container_name: factura-service1
    ports:
      - "8082"

  pago:
    image: pago
    container_name: pago-service1
    ports:
      - "8083"
